namespace AniT.App;

internal static class AnimeQuoteCatalog
{
    private static readonly string[] Quotes =
    [
        "Toda jornada começa com um primeiro passo.",
        "Mesmo a noite mais longa encontra o amanhecer.",
        "Coragem também é avançar com medo.",
        "Seu próximo capítulo ainda pode surpreender.",
        "Grandes amizades mudam qualquer destino.",
        "Um sonho protegido nunca caminha sozinho.",
        "Há força escondida em cada recomeço.",
        "O coração encontra caminhos que o mapa ignora.",
        "Nenhuma queda apaga tudo o que você aprendeu.",
        "Às vezes, vencer é simplesmente continuar.",
        "A esperança brilha melhor depois da tempestade.",
        "Cada escolha desenha um novo futuro.",
        "Quem protege alguém descobre a própria força.",
        "Até pequenos gestos podem mudar um mundo.",
        "O impossível só precisa de uma nova estratégia.",
        "Sua história merece mais uma tentativa.",
        "A verdadeira aventura acontece entre os encontros.",
        "Um rival também pode revelar seu melhor lado.",
        "Quando tudo muda, sua essência permanece.",
        "A luz mais distante ainda pode guiar você.",
        "Memórias felizes também são formas de coragem.",
        "Nenhum poder supera uma promessa sincera.",
        "O destino muda quando alguém decide agir.",
        "Existe beleza até nos caminhos inesperados.",
        "Toda despedida deixa uma nova direção.",
        "A confiança transforma passos em jornadas.",
        "Você não precisa enfrentar tudo sozinho.",
        "Até o silêncio pode guardar uma resposta.",
        "O amanhã começa nas decisões de hoje.",
        "Persistir também é uma forma de talento.",
        "Cada cicatriz conta que você continuou.",
        "O melhor time nasce de diferenças verdadeiras.",
        "Há mundos inteiros depois da próxima porta.",
        "Uma promessa pode atravessar qualquer distância.",
        "Ser gentil exige uma força especial.",
        "O medo diminui quando a amizade chega.",
        "Ninguém conhece o limite antes de tentar.",
        "Toda batalha ensina algo além da vitória.",
        "O coração se fortalece quando encontra propósito.",
        "Às vezes, perder o caminho revela outro sonho.",
        "A mudança começa quando você acredita nela.",
        "Uma nova temporada sempre traz novas escolhas.",
        "Mesmo longe, os laços continuam presentes.",
        "Toda equipe precisa de alguém que não desista.",
        "A resposta pode estar no próximo episódio.",
        "Não há aventura sem um pouco de incerteza.",
        "Seu ritmo também pode levar muito longe.",
        "A força cresce quando encontra uma razão.",
        "O passado ensina, mas não decide tudo.",
        "Uma boa história sempre encontra seu momento.",
        "Há coragem em pedir ajuda.",
        "Cada encontro deixa uma cor na memória.",
        "O horizonte pertence a quem segue olhando.",
        "Até um tropeço pode mudar a direção certa.",
        "Sonhos compartilhados ficam mais difíceis de quebrar.",
        "A verdadeira magia nasce do que você protege.",
        "Toda evolução começa fora da zona segura.",
        "Uma escolha honesta vale mais que mil atalhos.",
        "O tempo revela a força dos vínculos.",
        "Cada manhã oferece uma missão diferente.",
        "Não subestime o poder de um novo começo.",
        "A vitória mais importante acontece por dentro.",
        "Até heróis precisam descansar e recomeçar.",
        "Um passo sincero supera uma corrida sem rumo.",
        "Quem aprende a ouvir encontra novas respostas.",
        "A imaginação abre portas onde não havia paredes.",
        "Seu brilho não precisa parecer com o dos outros.",
        "Toda dúvida pode se transformar em descoberta.",
        "A melhor estratégia ainda precisa de coragem.",
        "O futuro guarda encontros que você ainda desconhece.",
        "Mesmo devagar, você continua escrevendo a história.",
        "Alguns milagres começam como decisões pequenas.",
        "Uma amizade verdadeira atravessa qualquer arco.",
        "O desconhecido também pode se tornar um lar.",
        "Cada desafio revela uma habilidade esquecida.",
        "Nunca é tarde para escolher outro caminho.",
        "O coração reconhece quem luta ao seu lado.",
        "Toda promessa pede coragem para ser cumprida.",
        "A paz também merece ser conquistada.",
        "Quem aceita mudar descobre novas versões de si.",
        "Até a menor chama pode iluminar uma equipe.",
        "A distância não apaga conexões verdadeiras.",
        "Toda história precisa de um momento de esperança.",
        "Seu próximo esforço pode mudar o resultado.",
        "As melhores respostas chegam durante a jornada.",
        "Um objetivo claro transforma qualquer treinamento.",
        "Há liberdade em criar o próprio destino.",
        "O mundo muda quando alguém escolhe cuidar.",
        "Cada temporada deixa algo para a próxima.",
        "A persistência encontra portas que a pressa ignora.",
        "Mesmo no caos, uma amizade pode florescer.",
        "O brilho de alguém também pode guiar outros.",
        "Toda aventura começa antes de sair de casa.",
        "A coragem cresce quando é dividida.",
        "Um novo episódio pode mudar toda a perspectiva.",
        "O caminho certo nem sempre é o mais fácil.",
        "Há poder em continuar sendo você.",
        "Cada final prepara silenciosamente outro início.",
        "A esperança sempre encontra uma brecha.",
        "Sua história continua enquanto houver vontade.",
    ];

    public static int Count => Quotes.Length;

    public static string GetFor(Guid animeId, string? aniListQuote = null)
    {
        if (!string.IsNullOrWhiteSpace(aniListQuote)) return aniListQuote.Trim();

        var hash = 2166136261u;
        foreach (var value in animeId.ToByteArray()) hash = (hash ^ value) * 16777619u;
        return Quotes[(int)(hash % (uint)Quotes.Length)];
    }
}
