<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\AniT.Core\AniT.Core.csproj" />
    <ProjectReference Include="..\AniT.Infrastructure\AniT.Infrastructure.csproj" />
    <ProjectReference Include="..\AniT.Player\AniT.Player.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
  </PropertyGroup>

  <ItemGroup>
    <Content Include="..\..\Player\MPC-HC\**\*" Link="Player\MPC-HC\%(RecursiveDir)%(Filename)%(Extension)" CopyToOutputDirectory="PreserveNewest" />
    <Resource Include="..\..\assets\baki-pi\Logo.png" Link="Assets\Logo.png" />
    <Resource Include="..\..\assets\baki-pi\Logo-sf.png" Link="Assets\Logo-sf.png" />
    <Resource Include="..\..\assets\logo-letter-white.png" Link="Assets\logo-letter-white.png" />
    <Resource Include="..\..\assets\ghost_menu.png" Link="Assets\ghost_menu.png" />
    <Resource Include="..\..\assets\ghost_popcorn.png" Link="Assets\ghost_popcorn.png" />
    <Resource Include="..\..\assets\fire.png" Link="Assets\fire.png" />
    <Resource Include="..\..\assets\baki-pi\normal-sf.png" Link="Assets\normal-sf.png" />
    <Resource Include="..\..\assets\baki-pi\angry-sf.png" Link="Assets\angry-sf.png" />
    <Resource Include="..\..\assets\baki-pi\sad-sf.png" Link="Assets\sad-sf.png" />
    <Resource Include="..\..\assets\baki-pi\boring-sf.png" Link="Assets\boring-sf.png" />
    <Resource Include="..\..\assets\baki-pi\happy2-sf.png" Link="Assets\happy2-sf.png" />
    <Resource Include="..\..\assets\baki-pi\happy-sf.png" Link="Assets\happy-sf.png" />
  </ItemGroup>

</Project>
