<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\AniT.Core\AniT.Core.csproj" />
    <ProjectReference Include="..\AniT.Infrastructure\AniT.Infrastructure.csproj" />
    <ProjectReference Include="..\AniT.Player\AniT.Player.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <ApplicationIcon>..\..\assets\anit.ico</ApplicationIcon>
  </PropertyGroup>

  <ItemGroup>
    <Content Include="..\..\Player\MPC-HC\**\*" Link="Player\MPC-HC\%(RecursiveDir)%(Filename)%(Extension)" CopyToOutputDirectory="PreserveNewest" />
    <Resource Include="..\..\assets\baki-pi\Logo.png" Link="Assets\Logo.png" />
    <Resource Include="..\..\assets\baki-pi\Logo-sf.png" Link="Assets\Logo-sf.png" />
    <Resource Include="..\..\assets\logo-letter-white.png" Link="Assets\logo-letter-white.png" />
    <Resource Include="..\..\assets\logo-fire.png" Link="Assets\logo-fire.png" />
    <Resource Include="..\..\assets\ghost_menu.png" Link="Assets\ghost_menu.png" />
    <Resource Include="..\..\assets\ghost_background.png" Link="Assets\ghost_background.png" />
    <Resource Include="..\..\assets\ghost_popcorn.png" Link="Assets\ghost_popcorn.png" />
    <Resource Include="..\..\assets\fire.png" Link="Assets\fire.png" />
    <Resource Include="..\..\assets\anit.ico" Link="Assets\anit.ico" />
    <Resource Include="..\..\assets\explore\backg.png" Link="Assets\Explore\backg.png" />
    <Resource Include="..\..\assets\explore\banner.png" Link="Assets\Explore\banner.png" />
    <Resource Include="..\..\assets\explore\1.png" Link="Assets\Explore\1.png" />
    <Resource Include="..\..\assets\explore\2.png" Link="Assets\Explore\2.png" />
    <Resource Include="..\..\assets\explore\3.png" Link="Assets\Explore\3.png" />
    <Resource Include="..\..\assets\explore\4.png" Link="Assets\Explore\4.png" />
    <Resource Include="..\..\assets\explore\5.png" Link="Assets\Explore\5.png" />
    <Resource Include="..\..\assets\explore\6.png" Link="Assets\Explore\6.png" />
    <Resource Include="..\..\assets\explore\7.png" Link="Assets\Explore\7.png" />
    <Resource Include="..\..\assets\explore\8.png" Link="Assets\Explore\8.png" />
    <Resource Include="..\..\assets\calendario\banner.png" Link="Assets\Calendar\banner.png" />
    <Resource Include="..\..\assets\calendario\samurai.png" Link="Assets\Calendar\samurai.png" />
    <Resource Include="..\..\assets\calendario\1.png" Link="Assets\Calendar\1.png" />
    <Resource Include="..\..\assets\calendario\2.png" Link="Assets\Calendar\2.png" />
    <Resource Include="..\..\assets\calendario\3.png" Link="Assets\Calendar\3.png" />
    <Resource Include="..\..\assets\calendario\4.png" Link="Assets\Calendar\4.png" />
    <Resource Include="..\..\assets\calendario\5.png" Link="Assets\Calendar\5.png" />
    <Resource Include="..\..\assets\calendario\6.png" Link="Assets\Calendar\6.png" />
    <Resource Include="..\..\assets\histórico\1.png" Link="Assets\History\1.png" />
    <Resource Include="..\..\assets\histórico\2.png" Link="Assets\History\2.png" />
    <Resource Include="..\..\assets\histórico\3.png" Link="Assets\History\3.png" />
    <Resource Include="..\..\assets\histórico\4.png" Link="Assets\History\4.png" />
    <Resource Include="..\..\assets\perfil\1.png" Link="Assets\Profile\1.png" />
    <Resource Include="..\..\assets\perfil\2.png" Link="Assets\Profile\2.png" />
    <Resource Include="..\..\assets\badges\**\*" Link="Assets\Badges\%(RecursiveDir)%(Filename)%(Extension)" />
    <Resource Include="..\..\assets\baki-pi\normal-sf.png" Link="Assets\normal-sf.png" />
    <Resource Include="..\..\assets\baki-pi\angry-sf.png" Link="Assets\angry-sf.png" />
    <Resource Include="..\..\assets\baki-pi\sad-sf.png" Link="Assets\sad-sf.png" />
    <Resource Include="..\..\assets\baki-pi\boring-sf.png" Link="Assets\boring-sf.png" />
    <Resource Include="..\..\assets\baki-pi\happy2-sf.png" Link="Assets\happy2-sf.png" />
    <Resource Include="..\..\assets\baki-pi\happy-sf.png" Link="Assets\happy-sf.png" />
  </ItemGroup>

</Project>
