<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\AniT.Core\AniT.Core.csproj" />
    <ProjectReference Include="..\AniT.Infrastructure\AniT.Infrastructure.csproj" />
    <ProjectReference Include="..\AniT.Player\AniT.Player.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
  </PropertyGroup>

  <ItemGroup>
    <Content Include="..\..\Player\MPC-HC\**\*" Link="Player\MPC-HC\%(RecursiveDir)%(Filename)%(Extension)" CopyToOutputDirectory="PreserveNewest" />
    <Content Include="..\..\assets\baki-pi\Logo.png" Link="Assets\Logo.png" CopyToOutputDirectory="PreserveNewest" />
    <Content Include="..\..\assets\baki-pi\Logo-sf.png" Link="Assets\Logo-sf.png" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>

</Project>
